package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        maven {
            name = "cleanMvn"
            enabled = false
            goals = "clean"
            mavenVersion = defaultProvidedVersion()
        }
        maven {
            name = "stepCH"
            goals = "mvn package -P ${'$'}{app_profile}"
            mavenVersion = defaultProvidedVersion()
        }
    }
    steps {
        update<MavenBuildStep>(1) {
            goals = "package -P ${'$'}{app_profile}"
        }
    }
}
